#!/bin/bash

# Copyright by Lars Geyer-Blaumeiser <lars@lgblaumeiser.de>
#
# Licensed under MIT license
#
# SPDX-License-Identifier: MIT

java -Dptm.host=localhost -Dptm.port=27727 -jar $PTM_HOME/ptm_cli-1.2.jar "$@"